# Generated by Django 4.0.6 on 2022-07-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceadmin', '0002_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
